# 默认参数
max_limit: 2 # 接口提示盖楼频繁最大限制次数，达到限制将休眠 10 秒后请求, 默认最大限制 5s 2次
ticker_duration: 2000 # 单位毫秒, 默认 1 秒请求一次, 小于 1000 进入极速模式适用于短时间抢楼

# 必填参数
url: 'https://bbplanet.bilibili.co/api/planet/comment/publish' # 盖楼接口 URL
article_business_id: '' # payload 中获取
xcsrf: '' # headers 中获取
cookie: '' # headers 中获取

# 可选参数
timing: # 定时器
  enable: false # 是否开启定时器, 默认关闭
  start_time: '' # 盖楼开始时间 '2022-07-22 22:00:00', 与 end_time 没有依赖关系可单独设置
  end_time: '' # 盖楼结束时间 '2022-07-22 23:00:00', 与 start_time 没有依赖关系可单独设置
trigger_building: # 盖楼触发器
  enable: false # 是否开启触发器, 默认关闭
  url: 'https://bbplanet.bilibili.co/api/planet/comment/commentList' # 评论列表接口 URL
  num: 0 # 触发盖楼的楼层数, MAX(楼层数) >= n 时开始盖楼
target_floor: # 盖中指定楼层
  enable: false
  nums: [] # 目标楼层, 默认为空
target_floor_rule: # 盖中规则匹配上的目标楼层
  enable: false
  rule: 1 # 目标规则, 1: 指定数的倍数; 2: 包含 target 字符
  target: 2 # 目标数字, 如 rule 指定 1, 表示所有 2 的倍数都选座目标楼层
target_floor_scope: # 盖中目标楼层返回
  enable: false
  url: 'https://bbplanet.bilibili.co/api/planet/comment/commentList' # 评论列表接口 URL
  min: 0
  max: 0
